### ISSUE TITLE
Can not run the code correctly

### ISSUE THREAD

**Issue by zhuqunxi** [YunzhuLi/CompositionalKoopmanOperators#3]
Hi, Yunzhu, I run the following command in my windows computer with some bug. Do you know how to fix it. Thanks advance.

(base) C:\Users\v-qunxizhu\OneDrive - Microsoft\Desktop\zqx\code\CompositionalKoopmanOperators-master\CompositionalKoopmanOperators-master>python eval.py --env Rope --pstep 2 --g_dim 32 --len_seq 64 --I_factor 10 --fit_type structured --fit_num 8 --eval_set demo
===== Experiment Configuration =====
env: Rope
dt: 0.02
pstep: 2
nf_relation: 120
nf_particle: 100
nf_effect: 100
g_dim: 32
fit_type: structured
attr_dim: 2
state_dim: 4
action_dim: 1
relation_dim: 8
baseline: False
baseline_order: 3
dataf: data/data_Rope
regular_data: 0
num_workers: 10
gen_data: 0
gen_stat: 1
group_size: 25
outf: dump_Rope/train_Rope_CKO_demo
lr: 0.0001
batch_size: 8
grad_clip: 5.0
n_epoch: 1000
beta1: 0.9
log_per_iter: 100
ckp_per_iter: 1000
resume_epoch: -1
resume_iter: -1
lambda_loss_metric: 0.3
len_seq: 64
I_factor: 10.0
fit_num: 8
eval: 0
evalf: dump_Rope/eval_Rope_CKO_demo
eval_type: koopman
eval_epoch: -1
eval_iter: -1
eval_set: demo
shootf: dump_Rope/shoot_Rope_CKO_demo
optim_iter_init: 100
optim_iter: 10
optim_type: qp
feedback: 1
shoot_set: valid
roll_start: 0
roll_step: 40
shoot_epoch: -1
shoot_iter: -1
data_names: ['attrs', 'states', 'actions']
n_rollout: 10000
train_valid_ratio: 0.9
time_step: 101
param_dim: 5
n_splits: 5
num_obj_range: [5, 6, 7, 8, 9]
extra_num_obj_range: [10, 11, 12, 13, 14]
act_scale: 2.0
demo: True
tmpf: dump_Rope/tmp
stat_path: data/data_Rope/stat_demo.h5
====================================
Load stored dataset statistics from data/data_Rope/stat_demo.h5!
The syntax of the command is incorrect.
Loading saved checkpoint from dump_Rope/train_Rope_CKO_demo\net_best.pth

=== Forward Simulation on Example 0 ===
Save video as dump_Rope/eval_Rope_CKO_demo\0.pred.avi
Save images to dump_Rope/eval_Rope_CKO_demo\0.pred_img
The syntax of the command is incorrect.
Traceback (most recent call last):
  File "eval.py", line 197, in <module>
    eval(roll_idx)
  File "eval.py", line 182, in eval
    engine.render(states_pred, seq_data[2], param, act_scale=args.act_scale, video=True, image=True,
  File "C:\Users\v-qunxizhu\OneDrive - Microsoft\Desktop\zqx\code\CompositionalKoopmanOperators-master\CompositionalKoopmanOperators-master\physics_engine.py", line 275, in render
    frame = frame.reshape(fig.canvas.get_width_height()[::-1] + (3,))
ValueError: cannot reshape array of size 3686400 into shape (480,640,3)

**Comment by YunzhuLi** [comment]
Hi Qunxi, which script were you running? According to your command, I suppose that you are running `scripts/eval_Rope.sh`. I have double-checked the script on my own machine, and it works as expected.

From your printed log, there is one line saying, "The syntax of the command is incorrect." Could this be the source of the issue?

**Comment by Zihang-He** [comment]
I encountered the same problem, but my log doesn't say "The syntax of the command is incorrect." it just reported the reshape error. I fixed the problem by adding matplotlib.use("Agg") and it worked.
