### ISSUE TITLE
Please change `Vec2d((x,y))` in `physics_engine.py` to `Vec2d(x,y)`

### ISSUE THREAD

**Issue by cookiegg** [YunzhuLi/CompositionalKoopmanOperators#4]
In pymunk6.0.0, Vec2d no longer accepts objects that have `.x` and `.y` properties. `Vec2d((x,y))` should be rewrite as `Vec2d(x, y)`

**Comment by YunzhuLi** [comment]
Good catch! Thank you for raising the issue, and I have updated the code to accommodate the upgrade of Pymunk to 6.0.0
